name: Mirror to Azure Repository

on:
  push:
    branches:
      - main
      - staging
      - devqa

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to Azure Repository
        env:
          AZURE_PAT_URL: ${{ secrets.AZURE_PAT_URL }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add azure $AZURE_PAT_URL

          for branch in main staging devqa; do
            git checkout $branch
            git push azure HEAD:$branch
          done
